//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReactMvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Word
    {
        public int Id { get; set; }
        public string French { get; set; }
        public string Vietnam { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string owner { get; set; }
        public Nullable<int> NumberRead { get; set; }
        public string Prononciation { get; set; }
        public string Exemple { get; set; }

    }
}
